/**
 * MyLassi.XYZ
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Develop
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateLessonPageOption model module.
 * @module model/CreateLessonPageOption
 * @version Develop
 */
class CreateLessonPageOption {
    /**
     * Constructs a new <code>CreateLessonPageOption</code>.
     * @alias module:model/CreateLessonPageOption
     */
    constructor() { 
        
        CreateLessonPageOption.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateLessonPageOption</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateLessonPageOption} obj Optional instance to populate.
     * @return {module:model/CreateLessonPageOption} The populated <code>CreateLessonPageOption</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateLessonPageOption();

            if (data.hasOwnProperty('base_template_id')) {
                obj['base_template_id'] = ApiClient.convertToType(data['base_template_id'], 'Number');
            }
            if (data.hasOwnProperty('note')) {
                obj['note'] = ApiClient.convertToType(data['note'], 'String');
            }
            if (data.hasOwnProperty('previous_page')) {
                obj['previous_page'] = ApiClient.convertToType(data['previous_page'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} base_template_id
 */
CreateLessonPageOption.prototype['base_template_id'] = undefined;

/**
 * @member {String} note
 */
CreateLessonPageOption.prototype['note'] = undefined;

/**
 * @member {Number} previous_page
 */
CreateLessonPageOption.prototype['previous_page'] = undefined;






export default CreateLessonPageOption;

