/**
 * MyLassi.XYZ
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Develop
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ExerciseInfo model module.
 * @module model/ExerciseInfo
 * @version Develop
 */
class ExerciseInfo {
    /**
     * Constructs a new <code>ExerciseInfo</code>.
     * @alias module:model/ExerciseInfo
     * @param id {Number} 
     * @param ownerId {Number} 
     * @param _public {Boolean} 
     * @param title {String} 
     */
    constructor(id, ownerId, _public, title) { 
        
        ExerciseInfo.initialize(this, id, ownerId, _public, title);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, ownerId, _public, title) { 
        obj['id'] = id;
        obj['owner_id'] = ownerId;
        obj['public'] = _public;
        obj['title'] = title;
    }

    /**
     * Constructs a <code>ExerciseInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ExerciseInfo} obj Optional instance to populate.
     * @return {module:model/ExerciseInfo} The populated <code>ExerciseInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExerciseInfo();

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('level')) {
                obj['level'] = ApiClient.convertToType(data['level'], 'String');
            }
            if (data.hasOwnProperty('owner_id')) {
                obj['owner_id'] = ApiClient.convertToType(data['owner_id'], 'Number');
            }
            if (data.hasOwnProperty('public')) {
                obj['public'] = ApiClient.convertToType(data['public'], 'Boolean');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} description
 */
ExerciseInfo.prototype['description'] = undefined;

/**
 * @member {Number} id
 */
ExerciseInfo.prototype['id'] = undefined;

/**
 * @member {String} level
 */
ExerciseInfo.prototype['level'] = undefined;

/**
 * @member {Number} owner_id
 */
ExerciseInfo.prototype['owner_id'] = undefined;

/**
 * @member {Boolean} public
 */
ExerciseInfo.prototype['public'] = undefined;

/**
 * @member {String} title
 */
ExerciseInfo.prototype['title'] = undefined;






export default ExerciseInfo;

