/**
 * MyLassi.XYZ
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Develop
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LessonPageTemplateInfo model module.
 * @module model/LessonPageTemplateInfo
 * @version Develop
 */
class LessonPageTemplateInfo {
    /**
     * Constructs a new <code>LessonPageTemplateInfo</code>.
     * @alias module:model/LessonPageTemplateInfo
     * @param id {Number} 
     * @param name {String} 
     * @param ownerId {Number} 
     */
    constructor(id, name, ownerId) { 
        
        LessonPageTemplateInfo.initialize(this, id, name, ownerId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, ownerId) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['owner_id'] = ownerId;
    }

    /**
     * Constructs a <code>LessonPageTemplateInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LessonPageTemplateInfo} obj Optional instance to populate.
     * @return {module:model/LessonPageTemplateInfo} The populated <code>LessonPageTemplateInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LessonPageTemplateInfo();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('owner_id')) {
                obj['owner_id'] = ApiClient.convertToType(data['owner_id'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
LessonPageTemplateInfo.prototype['id'] = undefined;

/**
 * @member {String} name
 */
LessonPageTemplateInfo.prototype['name'] = undefined;

/**
 * @member {Number} owner_id
 */
LessonPageTemplateInfo.prototype['owner_id'] = undefined;






export default LessonPageTemplateInfo;

