/**
 * MyLassi.XYZ
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Develop
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LessonPageVariable model module.
 * @module model/LessonPageVariable
 * @version Develop
 */
class LessonPageVariable {
    /**
     * Constructs a new <code>LessonPageVariable</code>.
     * @alias module:model/LessonPageVariable
     * @param content {String} 
     * @param name {String} 
     */
    constructor(content, name) { 
        
        LessonPageVariable.initialize(this, content, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, content, name) { 
        obj['content'] = content;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>LessonPageVariable</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LessonPageVariable} obj Optional instance to populate.
     * @return {module:model/LessonPageVariable} The populated <code>LessonPageVariable</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LessonPageVariable();

            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} content
 */
LessonPageVariable.prototype['content'] = undefined;

/**
 * @member {String} name
 */
LessonPageVariable.prototype['name'] = undefined;






export default LessonPageVariable;

