/**
 * MyLassi.XYZ
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Develop
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LessonPageTemplate model module.
 * @module model/LessonPageTemplate
 * @version Develop
 */
class LessonPageTemplate {
    /**
     * Constructs a new <code>LessonPageTemplate</code>.
     * @alias module:model/LessonPageTemplate
     * @param html {String} 
     * @param id {Number} 
     * @param name {String} 
     * @param ownerId {Number} 
     * @param _public {Boolean} 
     */
    constructor(html, id, name, ownerId, _public) { 
        
        LessonPageTemplate.initialize(this, html, id, name, ownerId, _public);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, html, id, name, ownerId, _public) { 
        obj['html'] = html;
        obj['id'] = id;
        obj['name'] = name;
        obj['owner_id'] = ownerId;
        obj['public'] = _public;
    }

    /**
     * Constructs a <code>LessonPageTemplate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LessonPageTemplate} obj Optional instance to populate.
     * @return {module:model/LessonPageTemplate} The populated <code>LessonPageTemplate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LessonPageTemplate();

            if (data.hasOwnProperty('html')) {
                obj['html'] = ApiClient.convertToType(data['html'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('owner_id')) {
                obj['owner_id'] = ApiClient.convertToType(data['owner_id'], 'Number');
            }
            if (data.hasOwnProperty('public')) {
                obj['public'] = ApiClient.convertToType(data['public'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} html
 */
LessonPageTemplate.prototype['html'] = undefined;

/**
 * @member {Number} id
 */
LessonPageTemplate.prototype['id'] = undefined;

/**
 * @member {String} name
 */
LessonPageTemplate.prototype['name'] = undefined;

/**
 * @member {Number} owner_id
 */
LessonPageTemplate.prototype['owner_id'] = undefined;

/**
 * @member {Boolean} public
 */
LessonPageTemplate.prototype['public'] = undefined;






export default LessonPageTemplate;

