/**
 * MyLassi.XYZ
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Develop
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LessonPagePublic from './LessonPagePublic';

/**
 * The LessonPublic model module.
 * @module model/LessonPublic
 * @version Develop
 */
class LessonPublic {
    /**
     * Constructs a new <code>LessonPublic</code>.
     * @alias module:model/LessonPublic
     * @param name {String} 
     * @param publicId {String} 
     */
    constructor(name, publicId) { 
        
        LessonPublic.initialize(this, name, publicId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, publicId) { 
        obj['name'] = name;
        obj['public_id'] = publicId;
    }

    /**
     * Constructs a <code>LessonPublic</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LessonPublic} obj Optional instance to populate.
     * @return {module:model/LessonPublic} The populated <code>LessonPublic</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LessonPublic();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('pages')) {
                obj['pages'] = ApiClient.convertToType(data['pages'], [LessonPagePublic]);
            }
            if (data.hasOwnProperty('public_id')) {
                obj['public_id'] = ApiClient.convertToType(data['public_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
LessonPublic.prototype['name'] = undefined;

/**
 * @member {Array.<module:model/LessonPagePublic>} pages
 */
LessonPublic.prototype['pages'] = undefined;

/**
 * @member {String} public_id
 */
LessonPublic.prototype['public_id'] = undefined;






export default LessonPublic;

