/**
 * MyLassi.XYZ
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Develop
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LessonPageTemplate from './LessonPageTemplate';
import LessonPageVariable from './LessonPageVariable';

/**
 * The LessonPagePublic model module.
 * @module model/LessonPagePublic
 * @version Develop
 */
class LessonPagePublic {
    /**
     * Constructs a new <code>LessonPagePublic</code>.
     * @alias module:model/LessonPagePublic
     * @param order {Number} 
     */
    constructor(order) { 
        
        LessonPagePublic.initialize(this, order);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, order) { 
        obj['order'] = order;
    }

    /**
     * Constructs a <code>LessonPagePublic</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LessonPagePublic} obj Optional instance to populate.
     * @return {module:model/LessonPagePublic} The populated <code>LessonPagePublic</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LessonPagePublic();

            if (data.hasOwnProperty('base_template')) {
                obj['base_template'] = ApiClient.convertToType(data['base_template'], LessonPageTemplate);
            }
            if (data.hasOwnProperty('order')) {
                obj['order'] = ApiClient.convertToType(data['order'], 'Number');
            }
            if (data.hasOwnProperty('variables')) {
                obj['variables'] = ApiClient.convertToType(data['variables'], [LessonPageVariable]);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/LessonPageTemplate} base_template
 */
LessonPagePublic.prototype['base_template'] = undefined;

/**
 * @member {Number} order
 */
LessonPagePublic.prototype['order'] = undefined;

/**
 * @member {Array.<module:model/LessonPageVariable>} variables
 */
LessonPagePublic.prototype['variables'] = undefined;






export default LessonPagePublic;

