/**
 * MyLassi.XYZ
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Develop
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LessonPageTemplateOption model module.
 * @module model/LessonPageTemplateOption
 * @version Develop
 */
class LessonPageTemplateOption {
    /**
     * Constructs a new <code>LessonPageTemplateOption</code>.
     * @alias module:model/LessonPageTemplateOption
     */
    constructor() { 
        
        LessonPageTemplateOption.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LessonPageTemplateOption</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LessonPageTemplateOption} obj Optional instance to populate.
     * @return {module:model/LessonPageTemplateOption} The populated <code>LessonPageTemplateOption</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LessonPageTemplateOption();

            if (data.hasOwnProperty('html')) {
                obj['html'] = ApiClient.convertToType(data['html'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('public')) {
                obj['public'] = ApiClient.convertToType(data['public'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} html
 */
LessonPageTemplateOption.prototype['html'] = undefined;

/**
 * @member {String} name
 */
LessonPageTemplateOption.prototype['name'] = undefined;

/**
 * @member {Boolean} public
 */
LessonPageTemplateOption.prototype['public'] = undefined;






export default LessonPageTemplateOption;

