/**
 * MyLassi.XYZ
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Develop
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UserInfo from './UserInfo';

/**
 * The LoginResponseBody model module.
 * @module model/LoginResponseBody
 * @version Develop
 */
class LoginResponseBody {
    /**
     * Constructs a new <code>LoginResponseBody</code>.
     * @alias module:model/LoginResponseBody
     * @param token {String} 
     */
    constructor(token) { 
        
        LoginResponseBody.initialize(this, token);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, token) { 
        obj['token'] = token;
    }

    /**
     * Constructs a <code>LoginResponseBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LoginResponseBody} obj Optional instance to populate.
     * @return {module:model/LoginResponseBody} The populated <code>LoginResponseBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoginResponseBody();

            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = UserInfo.constructFromObject(data['user']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} token
 */
LoginResponseBody.prototype['token'] = undefined;

/**
 * @member {module:model/UserInfo} user
 */
LoginResponseBody.prototype['user'] = undefined;






export default LoginResponseBody;

