/**
 * MyLassi.XYZ
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Develop
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PollSession model module.
 * @module model/PollSession
 * @version Develop
 */
class PollSession {
    /**
     * Constructs a new <code>PollSession</code>.
     * @alias module:model/PollSession
     * @param isRunning {Boolean} 
     * @param name {String} 
     */
    constructor(isRunning, name) { 
        
        PollSession.initialize(this, isRunning, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, isRunning, name) { 
        obj['is_running'] = isRunning;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>PollSession</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PollSession} obj Optional instance to populate.
     * @return {module:model/PollSession} The populated <code>PollSession</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PollSession();

            if (data.hasOwnProperty('is_running')) {
                obj['is_running'] = ApiClient.convertToType(data['is_running'], 'Boolean');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('votes')) {
                obj['votes'] = ApiClient.convertToType(data['votes'], {'String': 'Number'});
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} is_running
 */
PollSession.prototype['is_running'] = undefined;

/**
 * @member {String} name
 */
PollSession.prototype['name'] = undefined;

/**
 * @member {Object.<String, Number>} votes
 */
PollSession.prototype['votes'] = undefined;






export default PollSession;

