/**
 * MyLassi.XYZ
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Develop
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Error from '../model/Error';
import LoginRequestBody from '../model/LoginRequestBody';
import LoginResponseBody from '../model/LoginResponseBody';

/**
* API service.
* @module api/APIApi
* @version Develop
*/
export default class APIApi {

    /**
    * Constructs a new APIApi. 
    * @alias module:api/APIApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the apiV2LoginPost operation.
     * @callback module:api/APIApi~apiV2LoginPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/LoginResponseBody} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/LoginRequestBody} loginRequestBody 
     * @param {module:api/APIApi~apiV2LoginPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/LoginResponseBody}
     */
    apiV2LoginPost(loginRequestBody, callback) {
      let postBody = loginRequestBody;
      // verify the required parameter 'loginRequestBody' is set
      if (loginRequestBody === undefined || loginRequestBody === null) {
        throw new Error("Missing the required parameter 'loginRequestBody' when calling apiV2LoginPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = LoginResponseBody;
      return this.apiClient.callApi(
        '/api/v2/login', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
