/**
 * MyLassi.XYZ
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Develop
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import CreateExerciseOptions from './model/CreateExerciseOptions';
import CreateLesson from './model/CreateLesson';
import CreateLessonPageOption from './model/CreateLessonPageOption';
import CreateLessonPageTemplate from './model/CreateLessonPageTemplate';
import CreatePollOptions from './model/CreatePollOptions';
import EditExerciseOptions from './model/EditExerciseOptions';
import Error from './model/Error';
import Exercise from './model/Exercise';
import ExerciseInfo from './model/ExerciseInfo';
import ExerciseList from './model/ExerciseList';
import File from './model/File';
import Image from './model/Image';
import ImageList from './model/ImageList';
import Lesson from './model/Lesson';
import LessonInfo from './model/LessonInfo';
import LessonList from './model/LessonList';
import LessonMultiplexToken from './model/LessonMultiplexToken';
import LessonPage from './model/LessonPage';
import LessonPageOption from './model/LessonPageOption';
import LessonPagePublic from './model/LessonPagePublic';
import LessonPageTemplate from './model/LessonPageTemplate';
import LessonPageTemplateInfo from './model/LessonPageTemplateInfo';
import LessonPageTemplateList from './model/LessonPageTemplateList';
import LessonPageTemplateOption from './model/LessonPageTemplateOption';
import LessonPageVariable from './model/LessonPageVariable';
import LessonPublic from './model/LessonPublic';
import LoginRequestBody from './model/LoginRequestBody';
import LoginResponseBody from './model/LoginResponseBody';
import PatchPollOptions from './model/PatchPollOptions';
import Poll from './model/Poll';
import PollLabel from './model/PollLabel';
import PollList from './model/PollList';
import PollSession from './model/PollSession';
import PollSessionInfo from './model/PollSessionInfo';
import UserInfo from './model/UserInfo';
import APIApi from './api/APIApi';
import ExercisesApi from './api/ExercisesApi';
import FilesApi from './api/FilesApi';
import ImagesApi from './api/ImagesApi';
import LessonPageTemplateApi from './api/LessonPageTemplateApi';
import LessonsApi from './api/LessonsApi';
import PollsApi from './api/PollsApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var MyLassiXyz = require('index'); // See note below*.
* var xxxSvc = new MyLassiXyz.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new MyLassiXyz.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new MyLassiXyz.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new MyLassiXyz.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version Develop
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The CreateExerciseOptions model constructor.
     * @property {module:model/CreateExerciseOptions}
     */
    CreateExerciseOptions,

    /**
     * The CreateLesson model constructor.
     * @property {module:model/CreateLesson}
     */
    CreateLesson,

    /**
     * The CreateLessonPageOption model constructor.
     * @property {module:model/CreateLessonPageOption}
     */
    CreateLessonPageOption,

    /**
     * The CreateLessonPageTemplate model constructor.
     * @property {module:model/CreateLessonPageTemplate}
     */
    CreateLessonPageTemplate,

    /**
     * The CreatePollOptions model constructor.
     * @property {module:model/CreatePollOptions}
     */
    CreatePollOptions,

    /**
     * The EditExerciseOptions model constructor.
     * @property {module:model/EditExerciseOptions}
     */
    EditExerciseOptions,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The Exercise model constructor.
     * @property {module:model/Exercise}
     */
    Exercise,

    /**
     * The ExerciseInfo model constructor.
     * @property {module:model/ExerciseInfo}
     */
    ExerciseInfo,

    /**
     * The ExerciseList model constructor.
     * @property {module:model/ExerciseList}
     */
    ExerciseList,

    /**
     * The File model constructor.
     * @property {module:model/File}
     */
    File,

    /**
     * The Image model constructor.
     * @property {module:model/Image}
     */
    Image,

    /**
     * The ImageList model constructor.
     * @property {module:model/ImageList}
     */
    ImageList,

    /**
     * The Lesson model constructor.
     * @property {module:model/Lesson}
     */
    Lesson,

    /**
     * The LessonInfo model constructor.
     * @property {module:model/LessonInfo}
     */
    LessonInfo,

    /**
     * The LessonList model constructor.
     * @property {module:model/LessonList}
     */
    LessonList,

    /**
     * The LessonMultiplexToken model constructor.
     * @property {module:model/LessonMultiplexToken}
     */
    LessonMultiplexToken,

    /**
     * The LessonPage model constructor.
     * @property {module:model/LessonPage}
     */
    LessonPage,

    /**
     * The LessonPageOption model constructor.
     * @property {module:model/LessonPageOption}
     */
    LessonPageOption,

    /**
     * The LessonPagePublic model constructor.
     * @property {module:model/LessonPagePublic}
     */
    LessonPagePublic,

    /**
     * The LessonPageTemplate model constructor.
     * @property {module:model/LessonPageTemplate}
     */
    LessonPageTemplate,

    /**
     * The LessonPageTemplateInfo model constructor.
     * @property {module:model/LessonPageTemplateInfo}
     */
    LessonPageTemplateInfo,

    /**
     * The LessonPageTemplateList model constructor.
     * @property {module:model/LessonPageTemplateList}
     */
    LessonPageTemplateList,

    /**
     * The LessonPageTemplateOption model constructor.
     * @property {module:model/LessonPageTemplateOption}
     */
    LessonPageTemplateOption,

    /**
     * The LessonPageVariable model constructor.
     * @property {module:model/LessonPageVariable}
     */
    LessonPageVariable,

    /**
     * The LessonPublic model constructor.
     * @property {module:model/LessonPublic}
     */
    LessonPublic,

    /**
     * The LoginRequestBody model constructor.
     * @property {module:model/LoginRequestBody}
     */
    LoginRequestBody,

    /**
     * The LoginResponseBody model constructor.
     * @property {module:model/LoginResponseBody}
     */
    LoginResponseBody,

    /**
     * The PatchPollOptions model constructor.
     * @property {module:model/PatchPollOptions}
     */
    PatchPollOptions,

    /**
     * The Poll model constructor.
     * @property {module:model/Poll}
     */
    Poll,

    /**
     * The PollLabel model constructor.
     * @property {module:model/PollLabel}
     */
    PollLabel,

    /**
     * The PollList model constructor.
     * @property {module:model/PollList}
     */
    PollList,

    /**
     * The PollSession model constructor.
     * @property {module:model/PollSession}
     */
    PollSession,

    /**
     * The PollSessionInfo model constructor.
     * @property {module:model/PollSessionInfo}
     */
    PollSessionInfo,

    /**
     * The UserInfo model constructor.
     * @property {module:model/UserInfo}
     */
    UserInfo,

    /**
    * The APIApi service constructor.
    * @property {module:api/APIApi}
    */
    APIApi,

    /**
    * The ExercisesApi service constructor.
    * @property {module:api/ExercisesApi}
    */
    ExercisesApi,

    /**
    * The FilesApi service constructor.
    * @property {module:api/FilesApi}
    */
    FilesApi,

    /**
    * The ImagesApi service constructor.
    * @property {module:api/ImagesApi}
    */
    ImagesApi,

    /**
    * The LessonPageTemplateApi service constructor.
    * @property {module:api/LessonPageTemplateApi}
    */
    LessonPageTemplateApi,

    /**
    * The LessonsApi service constructor.
    * @property {module:api/LessonsApi}
    */
    LessonsApi,

    /**
    * The PollsApi service constructor.
    * @property {module:api/PollsApi}
    */
    PollsApi
};
