/**
 * MyLassi.XYZ
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Develop
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MyLassiXyz);
  }
}(this, function(expect, MyLassiXyz) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MyLassiXyz.LessonPageTemplateApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LessonPageTemplateApi', function() {
    describe('apiV2LessonsPageTemplatesDocIdGet', function() {
      it('should call apiV2LessonsPageTemplatesDocIdGet successfully', function(done) {
        //uncomment below and update the code to test apiV2LessonsPageTemplatesDocIdGet
        //instance.apiV2LessonsPageTemplatesDocIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiV2LessonsPageTemplatesDocIdPatch', function() {
      it('should call apiV2LessonsPageTemplatesDocIdPatch successfully', function(done) {
        //uncomment below and update the code to test apiV2LessonsPageTemplatesDocIdPatch
        //instance.apiV2LessonsPageTemplatesDocIdPatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiV2LessonsPageTemplatesGet', function() {
      it('should call apiV2LessonsPageTemplatesGet successfully', function(done) {
        //uncomment below and update the code to test apiV2LessonsPageTemplatesGet
        //instance.apiV2LessonsPageTemplatesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiV2LessonsPageTemplatesPost', function() {
      it('should call apiV2LessonsPageTemplatesPost successfully', function(done) {
        //uncomment below and update the code to test apiV2LessonsPageTemplatesPost
        //instance.apiV2LessonsPageTemplatesPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
